spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: outtaspace!!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: 