spring:
  datasource:
    url: '#{environment['url']}'
    username: '#{environment['username']}'
    password: '#{environment['password']}'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      # create-drop
      # update
      # validate 
      #  none
      # create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
